### ISSUE TITLE
random numbers not working

### ISSUE THREAD

**Issue by purvataranekar** [purvataranekar/dorarun#8]
https://github.com/purvataranekar/dorarun/edit/pause/js/1.js

**Comment by ishankhare07** [comment]
@purvataranekar provide more details like what is the actual problem or error in the javascript console?

**Comment by purvataranekar** [comment]
If random is added only once it works , while for the second time is does'nt

**Comment by ishankhare07** [comment]
you should look at the javascript console when it doesn't work and try to see what error message is displayed and on which line

**Comment by purvataranekar** [comment]
It says velocity function is not working but i didn't change anything related to it

**Comment by purvataranekar** [comment]
following code line have error
var x = Math.floor((Math.random() \* (10 - 0 + 1) + 0);
var y = Math.floor((Math.random() \* (20 - 10 + 1) + 10);
document.getElementById("random1").innerHTML= x;
document.getElementById("random2").innerHTML= y;

**Comment by purvataranekar** [comment]
![screenshot from 2015-04-05 19 13 08](https://cloud.githubusercontent.com/assets/8338335/6997024/da4a1a96-dbc7-11e4-84d8-9714a04bc75f.png)

**Comment by ishankhare07** [comment]
you've used extra ( in both of those lines
